---
id: 582506bf-7a23-4cda-b87c-8caaa298c511
---
graph TD
A[Design Verification] --> B[Pre Selicon Verification]
A --> C[Post Selicon Verification]
B --> D[Module Level Verification]
B --> E[System Level Verification]
D --> F[Simulation Based]
D --> G[Formal Based]
G --> H[Property Checking]
G --> I[Connectivity Checking]
D --> J[UVM Based]